name: dev deploy

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

env:
  IMAGE_NAME: baoleme-backend:${{ github.sha }}
  IMAGE_NAME_LATEST: baoleme-backend:latest

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag $env:IMAGE_NAME
    - name: Run Docker compose
      run: |
        docker compose -f scripts/ci-compose.yml up -d --wait
    - name: Run tests
      run: |
        docker exec baoleme-backend npm run test:unit
    - name: Save Docker image
      run: |
        docker tag $env:IMAGE_NAME $env:IMAGE_NAME_LATEST
        docker image save $env:IMAGE_NAME_LATEST -o baoleme-backend.tar
    - name: Upload Docker image
      uses: actions/upload-artifact@v4
      with:
        name: baoleme-backend
        path: baoleme-backend.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download Docker image
      uses: actions/download-artifact@v4
      with:
        name: baoleme-backend
    - name: Upload image to server
      uses: wlixcc/SFTP-Deploy-Action@v1.2.6
      with:
        username: ${{ vars.SSH_USER }}
        server: ${{ vars.SSH_HOST }}
        port: ${{ vars.SSH_PORT }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        local_path: ./baoleme-backend.tar
        remote_path: ~/images
    